### ISSUE TITLE
Unable to change colors in bar chart

### ISSUE THREAD

**Issue by ujvala-bhumi** [carlcraig/tc-angular-chartjs#79]
I m using 2.0.0 version of tc-angular-chartjs in my angular material project. I am able to display bar chart but when i apply colors to it, it is not effecting changes.

**Comment by carlcraig** [comment]
This is most likely due to 2.0.0 using Chart.js version 2.X 

Please could you look into the chart.js 2.x documentation to see if the required structures have changed.

http://www.chartjs.org/docs/
https://github.com/chartjs/Chart.js/issues

If there is a problem with this library, please re-open and we can investigate.
