### ISSUE TITLE
Conflict with chartjs-plugin-annotation?

### ISSUE THREAD

**Issue by cjwebdev** [carlcraig/tc-angular-chartjs#88]
I'm struggling to create annotations ( https://github.com/chartjs/chartjs-plugin-annotation )  in my Angular charts.

It should be OK?

**Comment by carlcraig** [comment]
Hi,

I believe this would not have worked due to lacking support of inline plugins.

PR #86 has now been merged, and a new version published to npm `v2.1.4`

If you upgrade to `v2.1.4` then the annotation plugin should work.

I will close this issue now, please re-open if you are still having problems.
